name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Build Images
      run: |
        ./services create || true
    - name: Run Script
      run: |
        ./services start test && ./services stop test
